# 데이터분석을 위한 중요 라이브러리 : numpy, pandas, matplotlib

<span style="color:blue;font-size:20px;font-weight:bold;">numpy</span>

In [ ]:
import numpy as np

numpy에서는 array라는 배열로 계산을 수행합니다  
여기에서는 [1, 2, 3, 4, 5]라는 요소를 가진 numpy의 배열 array를 준비합시다

### 실습환경 준비
> 주피터노트북에서 소수점이하 3자리로 제한  
> %precision 3

In [ ]:
1/3

In [ ]:
%precision 3
1/3

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

<b>크기</b>는 <b>shape</b>로 알 수 있습니다

In [ ]:
arr.shape                       

array에 대한 덧셈 연산을 해 봅시다

In [ ]:
arr + 2                                 

모든 요소에 2를 더했습니다  
이것을 <b>브로드캐스트</b>라고 합니다

덧셈 연산만이 아닌, 다른 연산자도 동일하게 방식으로 수행합니다  
제곱근을 취해 봅시다

In [ ]:
np.sqrt(arr)                                                                    

리스트와 마찬가지로 슬라이스로 요소를 추출할 수 있습니다  

In [ ]:
print(arr)
print('-----')                                                             
arr[:2]

In [ ]:
arr[3:5]

numpy의 arange 함수가 자주 사용됩니다  
arange 함수를 사용하여 [0, 1, 2, 3, 4]라는 요소를 가진 array를 간단히 작성할 수 있습니다

In [ ]:
np.arange(5)                 

arange 함수에는 <b>start, end, step</b>을 지정할 수 있습니다  
[2, 4, 6, 8]이라고 2씩 숫자가 증가하는 array는 다음과 같이 작성할 수 있습니다

In [ ]:
np.arange(2, 10, 2)

linspace 함수도 자주 사용합니다  
linspace 함수도 start부터 end까지의 array를 생성하는 함수이지만, step이 아닌 요소의 수를 지정합니다  
여기에서는 <b> 0부터 3까지 <font color=red>11 분할</font>한 array</b>를 만들어 봅시다

In [ ]:
np.linspace(0, 3, 11)                                                    

2차원 array도 간단히 생성합니다

In [ ]:
arr2 = np.array([[1, 3],
                 [5, 7]])                                          
arr2

In [ ]:
arr2.shape

<b>save 함수로 array를 저장</b>할 수 있습니다  
첫 번째 인수는 저장되는 이름이고, 두 번째 인수가 저장되는 array입니다

In [ ]:
np.save('test.npy', arr2)                                              

읽어들이는 것은 <b>load 함수</b>로 가능합니다

In [ ]:
np.load('test.npy')                          

## 배열 재구성
* numpy.array().reshape(튜플(행,열))

In [2]:
import numpy as np
ar = np.array([1,2,3,4,5,6,7,8,9])
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2 = ar.reshape(3,3)          
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr3 = ar.reshape(9,1)        
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 초기값 지정
*  numpy.zeros(튜(행,열))  

In [5]:
ar4 = np.zeros((2,3))           
ar4                              

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ar4 = np.ones((2,3)) 
ar4                                

array([[1., 1., 1.],
       [1., 1., 1.]])

## numpy 슬라이싱

In [ ]:
print('ar2 배열\n',arr2)
ar5 = arr2[1:2,1:2]
print('ar5 배열\n',ar5)                          
ar6 = arr2[1,:]
print('ar6 배열\n',ar6) 

## numpy 행렬곱

* numpy.dot()

In [ ]:
print(arr2)
ar7 = arr2[0:2,0:2]
print('ar7\n',ar7)
ar8 = arr2[1:3,1:3]
print('ar8\n',ar8)
ar9 = np.dot(ar7,ar8)
print('ar7 dot ar8\n',ar9)        

<span style="color:blue;font-size:20px;font-weight:bold;">pandas</span>

<span style="color:blue;font-size:16px;font-weight:bold;">
* pandas 임포트: import pandas as pd<br>
* pandas 1차원 자료구조: Series <br>
* pandas 2차원 자료구조: DataFrame <br>
* pandas 3차원 자료구조: Panel <br>    
* pandas 버전: pd.__version__<br>
</span>  


## 1차원 자료구조 생성

In [ ]:
import pandas as pd
data1 = [10,20,30,40,50]
data2 = ['1반','2반','3반','4반','5반']
sr1 = pd.Series(data1)
print('sr1\n',sr1)
sr2 = pd.Series(data2)
print('sr2\n',sr2)
sr3 = pd.Series([101,102,103,104,105])
print('sr3\n',sr3)
sr4 = pd.Series(['월','화','수','목','금'])      
print('sr4\n',sr4) 

## 인덱스를 지정하여 Series생성

In [ ]:
sr5 = pd.Series(data1,index=[1000,1001,1002,1003,1004])        
print('sr5\n',sr5)
sr6 = pd.Series(data1,index=data2)
print('sr6\n',sr6)

## Series 인덱싱, 슬라이싱

In [ ]:
# 인덱싱
print('sr6.iloc[2]\n',sr6.iloc[2])
print('sr6["3반"]\n',sr6['3반'])         
print('sr6.iloc[-1]\n',sr6.iloc[-1])              

# 슬라이싱
print('sr6.iloc[3:5]\n',sr6.iloc[3:5])

## Series 인덱스 및 값 구하기

In [ ]:
# 인덱스 구하기                                                  
sr6.index

In [ ]:
# 값 구하기                                                      
sr6.values

## Series 원소의 크기 및 값 Type이 같은 경우 연산 가능

In [ ]:
# 동일한 숫자 형태       
sr1 + sr3

In [ ]:
# 동일한 문자열 형태      
sr2 + sr4

## DataFrame 자료형

pandas는 pd라는 이름으로 임포트하는 것이 일반적입니다

In [ ]:
import pandas as pd

In [ ]:
# DataFrame 생성
테스트 = pd.DataFrame({'온도':[18,19,20,21,22,22.3,25]})      
테스트

In [ ]:
data = {
    'year' : [2019,2020,2021,2022,2023,2024],                                
    'sales' : [ 342,333,222,564,444,567]
}
df1 = pd.DataFrame(data)
df1

In [ ]:
df2 = pd.DataFrame([[67,85,99],[78,90,95]],index=['중간고사','기말고사'], columns=['1반','2반','3반'])     
df2

In [ ]:
data3 = [['20201101','Yoo','90','95'], ['20201102','kim','93','87'],['20201103','lee','87','98']]         
df3 = pd.DataFrame(data3)
df3

In [ ]:
df3.columns = ['학번','이름','중간고사','기말고사']          
df3

In [ ]:
df3.head(2)                                          

In [ ]:
df3.tail(2)                                   

In [ ]:
df3['이름']                      

In [ ]:
df3.to_csv('학생정보1.csv',header=True)     

In [ ]:
df4 = pd.read_csv('학생정보1.csv',encoding='utf-8',index_col=0,engine='python')   
df4

In [ ]:
usecols=['학번','이름','중간고사','기말고사']
df4 = pd.read_csv('학생정보1.csv',encoding='utf-8',index_col=0,usecols=usecols,skiprows=[1], engine='python')   
df4

In [ ]:
df4.loc[20201103,['이름','기말고사']]        

In [ ]:
df4.iloc[1]                                

In [76]:
df4.index                                                                      

Index([20201102, 20201103], dtype='int64', name='학번')

In [75]:
df4.columns                                                

Index(['이름', '중간고사', '기말고사'], dtype='object')

In [77]:
df4.values                                         

array([['kim', 93, 87],
       ['lee', 87, 98]], dtype=object)

In [74]:
df4.describe()

중간고사       기말고사
count   2.000000   2.000000
mean   90.000000  92.500000
std     4.242641   7.778175
min    87.000000  87.000000
25%    88.500000  89.750000
50%    90.000000  92.500000
75%    91.500000  95.250000
max    93.000000  98.000000

이 책의 제1장에서 사용하는 데이터를 읽어들입시다  
read_csv 함수를 사용하여 csv를 pandas의 DataFrame이라는 형식으로 읽어들일 수 있습니다  

### 실습환경준비
> DataFrame의 출력을 소수점 이하 3자리로 제한  
> pd.set_option('precision',3)


In [ ]:
df = pd.read_csv('sport_test.csv')
df

## 추출

이번은 DataFrame이 10행으로 비교적 소규모이지만, 수백행・수천행의 DataFrame을 다루는 경우도 흔한 일은 아닙니다  
DataFrame의 구조를 알기 위해서는 DataFrame의 <b><font color=blue>head 메서드</font></b>가 자주 사용됩니다  
head 메서드는 DataFrame의 앞 부분의 행을 추출하는 메서드입니다  
여기에서는 3행을 추출해봅시다

In [ ]:
df.head(3)

아무것도 지정하지 않으면 5행이 추출됩니다

In [ ]:
df.head()

마찬가지로 <b><font color=blue>tail 메서드</font></b>는 DataFrame의 뒷부분을 추출합니다

In [ ]:
df.tail()

<b><font color=blue>슬라이스로 추출</font></b>할 수도 있습니다

In [ ]:
df[2:5]

열은 <b><font color=blue>열 이름으로 추출</font></b>할 수 있습니다

In [ ]:
df['악력']

복수열을 동시에 지정할 수도 있습니다

In [ ]:
df[['학년', '점수']]

<b><font color=blue>행과 열을 동시에 지정하여 추출</font></b>하고 싶을 때에는 <b><font color=red>loc 메서드</font></b>가 편리합니다
예를 들어 첫 번째 행의 학년은 다음과 같이 추출할 수 있습니다

In [ ]:
df.loc[1, '학년']

슬라이스에 의한 지정도 가능합니다

In [ ]:
df.loc[1:3, '악력']

조건에 일치하는 행을 추출하고 싶은 경우는 다음과 같이 작성합니다  
여기에서는 악력이 30보다 작은 행을 추출합니다

In [ ]:
df[df['악력'] < 30]

## 데이터의 개요

데이터의 크기는 shape로 알 수 있습니다

In [ ]:
df.shape

<b>열 이름 확인</b>은 <b><font color=red>columns</font></b>입니다

In [ ]:
df.columns

<b>인덱스 확인</b>은 <b><font color=red>index</font></b>입니다.

In [ ]:
df.index

<b><font color=red>describe()함수</font>는 수치형 변수들만을 기준으로 카운트, 평균, 표준편차, 최소/최댓값, 4분위수를 기준으로 25%, 50%, 75% 해당하는 값을 테이블로 출력</b>

In [ ]:
df.describe()

## 데이터의 추가

df에 데이터를 추가해봅시다  
우선은 열의 추가입니다

In [ ]:
df['팔 굽혀 펴기'] = [15, 12, 10, 4, 20,
                  24, 9, 11, 11, 17]
df

다음은 행을 추가해보겠습니다

In [ ]:
new_row = pd.Series([11, 3, 42.4, 30, 15, 11, 12], index=df.columns, name=10)
new_row

In [ ]:
df.append(new_row)